''' RTT WebAssembly scons conifg
'''
import os
Import('env')

objs = [
    SConscript(os.path.join(d, 'SConscript'), exports='env')
    for d in os.listdir('.') if os.path.isfile(os.path.join('.', d, 'SConscript'))
]

Return('objs')
